#!/bin/bash
# simple script to create a ssbench message header
# and write it to stdout
# sbench message header is a binary 2 bytes little endian worker id
# followed by a binary 2 byte little endian queue id
# followed by a binary 4 byte little endian data length.
# This script assumes values are in decimal

w=$1
q=$2
len=$3

wbytes=$(printf "%04x" $w)
qbytes=$(printf "%04x" $q)
lbytes=$(printf "%08x" $len)

# little endian byte values 
echo -n -e "\x${wbytes:2:2}\x${wbytes:0:2}"
echo -n -e "\x${qbytes:2:2}\x${qbytes:0:2}"
echo -n -e "\x${lbytes:6:2}\x${lbytes:4:2}\x${lbytes:2:2}\x${lbytes:0:2}"
